# Generated by Django 5.2.4 on 2025-11-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuadrilla", "0004_registro_trabajo_estado_alter_registro_trabajo_fecha"),
        ("incidencia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuadrilla.cuadrilla",
                    ),
                ),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidencia.incidencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignacion",
                "verbose_name_plural": "Asignaciones",
                "ordering": ["fecha_asignacion"],
            },
        ),
    ]
