# Generated by Django 5.2.4 on 2025-10-01 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="correo_encargado",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="departamento",
            name="nombre_encargado",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
