# Generated by Django 5.2.4 on 2025-10-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0002_departamento_correo_encargado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departamento",
            name="correo_encargado",
        ),
        migrations.RemoveField(
            model_name="departamento",
            name="nombre_encargado",
        ),
    ]
