# Generated by Django 5.2.4 on 2025-10-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_remove_departamento_correo_encargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
