# Generated by Django 5.2.4 on 2025-10-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_departamento_activo'),
    ]

    operations = [
    ]
