# Generated by Django 5.2.4 on 2025-11-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0005_auto_20251009_2114"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departamento",
            name="activo",
        ),
    ]
