# Generated by Django 5.2.4 on 2025-09-30 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfiles",
            fields=[
                ("id_perfil", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Perfiles",
                "db_table": "perfiles",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=255, unique=True)),
                (
                    "id_perfil",
                    models.ForeignKey(
                        db_column="id_perfil",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="core.perfiles",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
            },
        ),
    ]
