# Generated by Django 5.2.4 on 2025-09-28 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_direccion", models.CharField(max_length=200)),
                ("nombre_encargado", models.CharField(blank=True, max_length=200)),
                ("correo_encargado", models.EmailField(blank=True, max_length=254)),
                (
                    "state",
                    models.CharField(
                        blank=True, default="Activo", max_length=100, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Direccion",
                "verbose_name_plural": "Direcciones",
                "ordering": ["nombre_direccion"],
            },
        ),
    ]
