# Generated by Django 5.2.4 on 2025-10-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direccion", "0002_alter_direccion_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="direccion",
            name="correo_encargado",
        ),
        migrations.RemoveField(
            model_name="direccion",
            name="nombre_encargado",
        ),
    ]
