# Generated by Django 5.2.4 on 2025-11-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuadrilla", "0001_initial"),
        ("incidencia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro_trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "Cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuadrillas",
                        to="cuadrilla.cuadrilla",
                    ),
                ),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="incidencia.incidencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro",
                "verbose_name_plural": "Registros",
                "ordering": ["incidencia"],
            },
        ),
    ]
