# Generated by Django 5.2.4 on 2025-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuadrilla", "0002_registro_trabajo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registro_trabajo",
            old_name="Cuadrilla",
            new_name="cuadrilla",
        ),
        migrations.AlterField(
            model_name="registro_trabajo",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
