# Generated by Django 5.2.4 on 2025-11-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuadrilla", "0003_rename_cuadrilla_registro_trabajo_cuadrilla_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro_trabajo",
            name="estado",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="registro_trabajo",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
