# Generated by Django 5.2.4 on 2025-11-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuadrilla", "0004_registro_trabajo_estado_alter_registro_trabajo_fecha"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultimediaRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("otro", "Otro"),
                        ],
                        default="imagen",
                        max_length=50,
                    ),
                ),
                ("path", models.FileField(upload_to="archivos_registros/%Y/%m/%d/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multimedia",
                        to="cuadrilla.registro_trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Multimedia",
                "verbose_name_plural": "Archivos Multimedia",
                "ordering": ["-created"],
            },
        ),
    ]
