# Generated by Django 5.2.4 on 2025-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]