# Generated by Django 5.2.4 on 2025-10-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamento", "0003_remove_departamento_correo_encargado_and_more"),
        ("encuesta", "0001_initial"),
        ("territorial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("tipo", models.CharField(blank=True, max_length=254)),
                ("ubicacion", models.CharField(blank=True, max_length=250, null=True)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "nombre_vecino",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "telefono_vecino",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "correo_vecino",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default="Activo", max_length=100, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamento.departamento",
                    ),
                ),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encuesta.encuesta",
                    ),
                ),
                (
                    "territorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="territorial.territorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidencia",
                "verbose_name_plural": "Incidencias",
                "ordering": ["titulo"],
            },
        ),
    ]
