# Generated by Django 5.2.4 on 2025-10-30 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultimediaIncidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("otro", "Otro"),
                        ],
                        default="imagen",
                        max_length=50,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(upload_to="archivos_incidencias/%Y/%m/%d/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multimedia",
                        to="incidencia.incidencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Multimedia",
                "verbose_name_plural": "Archivos Multimedia",
                "ordering": ["-created"],
            },
        ),
    ]
