# Generated by Django 5.2.4 on 2025-11-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                blank=True, default="Pendiente", max_length=100, null=True
            ),
        ),
    ]
