# Generated by Django 5.2.4 on 2025-10-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0002_multimediaincidencia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multimediaincidencia",
            old_name="archivo",
            new_name="path",
        ),
        migrations.AddField(
            model_name="multimediaincidencia",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
