# Generated by Django 5.2.4 on 2025-11-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0003_rename_archivo_multimediaincidencia_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Activo", "Activo (Pendiente)"),
                    ("Aceptado", "Aceptado"),
                    ("Rechazado", "Rechazado"),
                    ("Bloqueado", "Bloqueado"),
                ],
                default="Activo",
                max_length=100,
                null=True,
            ),
        ),
    ]
