# Generated by Django 5.2.4 on 2025-11-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0002_incidencia_estado"),
        ("incidencia", "0004_alter_incidencia_state"),
    ]

    operations = []
