# Generated by Django 5.2.4 on 2025-11-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0005_merge_20251114_0145"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidencia",
            name="estado",
        ),
        migrations.AlterField(
            model_name="incidencia",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Aceptado", "Aceptado"),
                    ("Rechazado", "Rechazado"),
                    ("Bloqueado", "Bloqueado"),
                    ("Asignada", "Asignada"),
                    ("Resuelto", "Resuelto"),
                ],
                default="Pendiente",
                max_length=100,
                null=True,
            ),
        ),
    ]
