# Generated by Django 5.2.7 on 2025-11-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0006_remove_incidencia_estado_alter_incidencia_state'),
        ('pregunta', '0003_alter_pregunta_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='state',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Bloqueado', 'Bloqueado'), ('Asignada', 'Asignada'), ('Resuelto', 'Resuelto'), ('Bloqueado', 'Bloqueado')], default='Pendiente', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RespuestaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_incidencia', to='incidencia.incidencia')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pregunta.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Incidencia',
                'verbose_name_plural': 'Respuestas de Incidencias',
                'unique_together': {('incidencia', 'pregunta')},
            },
        ),
    ]
