# Generated by Django 5.2.4 on 2025-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0006_remove_incidencia_estado_alter_incidencia_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                blank=True, default="Pendiente", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incidencia",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("Bloqueado", "Bloqueado")],
                default="Pendiente",
                max_length=100,
                null=True,
            ),
        ),
    ]
