# Generated by Django 5.2.4 on 2025-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0007_incidencia_estado_alter_incidencia_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("Bloqueado", "Bloqueado")],
                default="Activo",
                max_length=100,
                null=True,
            ),
        ),
    ]
