# Generated by Django 5.2.4 on 2025-11-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0008_alter_incidencia_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="state",
            field=models.CharField(
                blank=True, default="Activo", max_length=100, null=True
            ),
        ),
    ]
