# Generated by Django 5.2.4 on 2025-10-02 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Territorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zona_asignada",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True, default="Activo", max_length=100, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Territorial",
                "verbose_name_plural": "Territoriales",
                "ordering": ["usuario__username"],
            },
        ),
    ]
