# Generated by Django 5.2.4 on 2025-11-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("territorial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="territorial",
            name="observaciones",
        ),
    ]
