# Generated by Django 5.2.4 on 2025-11-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuesta", "0001_initial"),
        ("incidencia", "0001_initial"),
        ("pregunta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pregunta",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="contenido",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="created",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="state",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="created",
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="state",
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="updated",
        ),
        migrations.AddField(
            model_name="pregunta",
            name="encuesta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="encuesta.encuesta",
            ),
        ),
        migrations.AddField(
            model_name="respuesta",
            name="incidencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incidencia.incidencia",
            ),
        ),
        migrations.AlterField(
            model_name="respuesta",
            name="contenido",
            field=models.TextField(blank=True, null=True),
        ),
    ]
