# Generated by Django 5.2.4 on 2025-11-10 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuesta", "0001_initial"),
        ("pregunta", "0002_remove_pregunta_autor_remove_pregunta_contenido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="encuesta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="encuesta.encuesta",
            ),
        ),
    ]